// See https://aka.ms/new-console-template for more information
Console.WriteLine("Hello, World!");
//why does VS and github hate me so much????
//I should have practiced Git Bash so much more before....
//I have no idea what I'm doing.....